language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t elbum/react-test-app -f ./frontend/Dockerfile.dev ./frontend

script:
  - docker run -e CI=true elbum/react-test-app npm run test

after_success:
  - docker build -t elbum/docker-frontend ./frontend
  - docker build -t elbum/docker-backend ./backend
  - docker build -t elbum/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push elbum/docker-frontend
  - docker push elbum/docker-backend
  - docker push elbum/docker-nginx
  
